### ISSUE TITLE
Seele custom weapons

### ISSUE THREAD

**Issue by MrTheDragons** [Petrascyll/hsr-scripts#1]
Just saw it while updating everything with your tool, wich worked very well thanks for making it

I'm using this mod: https://gamebanana.com/mods/445810 , the skin itself is being fixed but not the custom weapon

Since i've seen your last changelog about some characters weapons i'm hoping you would be able to fix this one too

**Comment by Petrascyll** [comment]
Ah somehow forgot about Seele's scythe. I posted an update with a fix for her scythe's diffuse/lightmap hashes.

**Comment by MrTheDragons** [comment]
Works perfectly, thx
